Switch GitHub Actions to Windows 2025 runner
SDL is failing to build with:

    SDL\src\core\windows\SDL_gameinput.h(29,10): error C1083: Cannot open include file: 'gameinput.h': No such file or directory

It seems to be related to this issue:

https://github.com/libsdl-org/SDL/issues/11487

Which is fixed in the 2025 runner.